export default {
	login: "leontan4",
	id: 30102238,
	node_id: "MDQ6VXNlcjMwMTAyMjM4",
	avatar_url: "https://avatars.githubusercontent.com/u/30102238?v=4",
	gravatar_id: "",
	url: "https://api.github.com/users/leontan4",
	html_url: "https://github.com/leontan4",
	followers_url: "https://api.github.com/users/leontan4/followers",
	following_url: "https://api.github.com/users/leontan4/following{/other_user}",
	gists_url: "https://api.github.com/users/leontan4/gists{/gist_id}",
	starred_url: "https://api.github.com/users/leontan4/starred{/owner}{/repo}",
	subscriptions_url: "https://api.github.com/users/leontan4/subscriptions",
	organizations_url: "https://api.github.com/users/leontan4/orgs",
	repos_url: "https://api.github.com/users/leontan4/repos",
	events_url: "https://api.github.com/users/leontan4/events{/privacy}",
	received_events_url: "https://api.github.com/users/leontan4/received_events",
	type: "User",
	site_admin: false,
	name: "Leon Tan",
	company: "Student",
	blog: "https://leontan.netlify.app/",
	location: "Minneapolis, MN",
	email: null,
	hireable: true,
	bio: null,
	twitter_username: null,
	public_repos: 7,
	public_gists: 0,
	followers: 0,
	following: 0,
	created_at: "2017-07-12T04:20:15Z",
	updated_at: "2021-04-16T20:49:10Z",
};
